config/routes.rb
PatternLibrary::Engine.routes.draw do
  resources :patterns

  root to: 'patterns#index'
end

app/models/pattern_library/pattern.rb
module PatternLibrary
  class Pattern < ActiveRecord::Base

    default_scope { order :order }

    validates_presence_of :snippet
    validates_numericality_of :order, only_integer: true, greater_than_or_equal_to: 0
  end
end

app/controllers/pattern_library/application_controller.rb
module PatternLibrary
  class ApplicationController < ::ApplicationController
  end
end

app/controllers/pattern_library/patterns_controller.rb
require_dependency "pattern_library/application_controller"

module PatternLibrary
  class PatternsController < ApplicationController
    before_action :find_pattern, only: [:show, :edit, :update, :destroy]
    before_action :protect_builtin, only: [:edit, :update, :destroy]

    def index
      @patterns = Pattern.all
      render layout: layout
    end

    def show
    end

    def new
      @pattern = Pattern.new(order: Pattern.count)
    end

    def create
      @pattern = Pattern.new pattern_params
      if @pattern.save
        redirect_to patterns_path, notice: 'Pattern created successfully'
      else
        flash.now[:alert] = @pattern.errors.full_messages.join('. ')
        render :new
      end
    end

    def edit
    end

    def update
      if @pattern.update_attributes pattern_params
        redirect_to patterns_path, notice: 'Pattern updated successfully'
      else
        flash.now[:alert] = @pattern.errors.full_messages.join('. ')
        render :edit
      end
    end

    def destroy
      @pattern.destroy
      redirect_to patterns_path, notice: 'Pattern deleted'
    end

    private

    def layout
      params[:layout].present? ? params[:layout] : 'application'
    end

    def find_pattern
      @pattern = Pattern.find params[:id]
    end

    def protect_builtin
      redirect_to patterns_path unless @pattern.custom?
    end

    def pattern_params
      params.require(:pattern).permit :snippet, :usage, :order
    end
  end
end

app/helpers/pattern_library/application_helper.rb
module PatternLibrary
  module ApplicationHelper
    def method_missing(method, *args, &block)
      method_name = method.to_s
      if (method_name.end_with?('_path') || method_name.end_with?('_url')) && main_app.respond_to?(method)
        main_app.send method, *args
      else
        super
      end
    end
  end
end

app/helpers/pattern_library/patterns_helper.rb
module PatternLibrary
  module PatternsHelper
  end
end

app/views/pattern_library/patterns/_form.html.erb
<div id="pl-pattern-form">
  <%= form_for @pattern do |f| %>
    <div class="field">
      <%= f.label :snippet %>
      <%= f.text_area :snippet, rows: 10, cols: 100 %>
    </div>
    <div class="field">
      <%= f.label :usage, 'Usage (optional)' %>
      <%= f.text_area :usage, rows: 10, cols: 100 %>
    </div>
    <%= f.hidden_field :order %>
    <div class="actions">
      <%= f.submit %>
      |
      <%= link_to 'Cancel', patterns_path %>
    </div>
  <% end %>
</div>

app/views/pattern_library/patterns/_pattern.html.erb
<div class="pl-pattern">
  <div class="pl-pattern-html">
    <pre class="pl-snippet"><%= pattern.snippet %></pre>
    <div class="pl-snippet-styled">
      <%= pattern.snippet.html_safe %>
    </div>
  </div>
  <pre class="pl-pattern-css">
  </pre>
  <div class="pl-actions">
    <% if pattern.usage.present? && !current_page?(pattern_path(pattern)) %>
      <%= link_to 'Usage details', pattern_path(pattern) %>
      <% if pattern.custom? %>
        |
      <% end %>
    <% end %>
    <% if pattern.custom? %>
      <%= link_to 'Edit Pattern', edit_pattern_path(pattern) %> |
      <%= form_for pattern, method: :delete do |f| %>
        <%= f.submit 'Delete Pattern' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pattern_library/patterns/edit.html.erb
<h1>Edit Pattern</h1>

<%= render 'form' %>

app/views/pattern_library/patterns/index.html.erb
<h1>Patterns</h1>

<div id="pl-patterns">
  <% @patterns.each do |pattern| %>
    <%= render pattern %>
  <% end %>
</div>

<div id="pl-actions">
  <p><%= link_to 'Create Pattern', new_pattern_path %></p>
</div>

app/views/pattern_library/patterns/new.html.erb
<h1>Create Pattern</h1>

<%= render 'form' %>

app/views/pattern_library/patterns/show.html.erb
<h1>Pattern</h1>

<div id="pl-patterns">
  <%= render @pattern %>
  <h2>Usage</h2>
  <div class="pl-pattern">
    <%= @pattern.usage %>
  </div>
</div>

<div id="pl-actions">
  <p><%= link_to 'Back to list', patterns_path %></p>
</div>